### ISSUE TITLE
Panic from child threads

### ISSUE THREAD

**Issue by palfrey** [boonshift/gstats#1]
The main thread went `thread 'main' panicked at 'oops! the child thread panicked: Any', src/libcore/result.rs:1165:5` and I had several like the following:
``thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -9, klass: 4, message: "reference \'refs/heads/master\' not found" }', src/libcore/result.rs:1165:5``

**Comment by boonshift** [comment]
Sorry, didn't check until now. Will take a look asap.

**Comment by boonshift** [comment]
Should be fixed in 0.1.4. It was an error when going through git directories with no HEAD (no commits).

**Comment by palfrey** [comment]
Now seems fixed to me
